# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:
  - version
  - build
  - package
  - screenshots
  - testflight
  - release

default:
  before_script:
    - "export LC_ALL=en_US.UTF-8"
    - "export LANG=en_US.UTF-8"
    - "export JAVA_HOME=/usr/local/opt/openjdk@21"
    - 'eval "$(rbenv init - --no-rehash zsh)"'
    - 'export SELENE_VERSION=$(grep -o ''"version": *"[^"]*"'' package.json | sed -e ''s/"version": *"//'' -e ''s/"$//'')'
    - 'echo "SELENE_VERSION $SELENE_VERSION"'

version:
  stage: version
  script:
    - scripts/chversion
  only:
    - main
    - testflight
  tags:
    - macos

# Build
build_sync:
  stage: build
  image: node:lts-alpine
  script:
    - 'apk add git'
    - yarn install
    - yarn build
    - npx cap sync
  artifacts:
    paths:
      - "dist/"
      - "node_modules/**/*capacitor*"
      - "android/"
      - "ios/"

# Screenshots
screenshots_android:
  stage: screenshots
  script:
    - cd android/
    - bundle install
    - bundle exec fastlane snapshot
  artifacts:
    paths:
      - android/fastlane/screenshots
  only:
    - main
  tags:
    - macos

screenshots_ios:
  stage: screenshots
  script:
    - cd ios/App/
    - bundle install
    - bundle exec fastlane snapshot
  artifacts:
    paths:
      - ios/App/fastlane/screenshots
  only:
    - main
  tags:
    - macos

# Android Packaging
package_android:
  stage: package
  dependencies:
    - build_sync
  script:
    - cd android/
    - bundle install
    - bundle exec fastlane package
  artifacts:
    paths:
      - android/app/build/outputs/apk/release/app-release.apk
      - android/app/build/outputs/bundle/release/app-bundle.aab
    expire_in: 1 year
  only:
    - main
    - testflight
  tags:
    - macos

package_android_edge:
  stage: package
  dependencies:
    - build_sync
  script:
    - cd android/
    - bundle install
    - bundle exec fastlane package_debug
  artifacts:
    paths:
      - android/app/build/outputs/apk/debug/app-debug.apk
  only:
    - edge
  tags:
    - macos

# Android Deployment
deploy_android_edge:
  stage: release
  image: alpine:latest
  dependencies:
    - package_android_edge
  script:
    - "which ssh-agent || (apk update && apk add openssh)"
    - "mkdir -p ~/.ssh && chmod 700 ~/.ssh"
    - eval $(ssh-agent -s)
    - echo "$SELENE_SSH_KEY_BASE64" | base64 -d | ssh-add - > /dev/null 2>&1
    - echo "$SSH_KNOWN_HOSTS_BASE64" | base64 -d > ~/.ssh/known_hosts
    - echo "Uploading selene-edge.apk"
    - scp android/app/build/outputs/apk/debug/app-debug.apk selene@warpgate.selene.technology:/srv/www/selene.cash/public/download/selene-edge.apk
  only:
    - edge

deploy_android_apk:
  stage: release
  image: alpine:latest
  dependencies:
    - package_android
  script:
    - "which ssh-agent || (apk update && apk add openssh)"
    - "mkdir -p ~/.ssh && chmod 700 ~/.ssh"
    - eval $(ssh-agent -s)
    - echo "$SELENE_SSH_KEY_BASE64" | base64 -d | ssh-add - > /dev/null 2>&1
    - echo "$SSH_KNOWN_HOSTS_BASE64" | base64 -d > ~/.ssh/known_hosts
    - echo "Uploading selene-v$SELENE_VERSION.apk"
    - scp android/build/app/outputs/apk/release/app-release.apk selene@warpgate.selene.technology:/srv/www/selene.cash/public/download/selene-v$SELENE_VERSION.apk
    # update remote nginx config here
  only:
    - main

deploy_android_release:
  stage: release
  dependencies:
    - package_android
    - screenshots_android
  script:
    - cd android/
    - bundle install
    - bundle exec fastlane deploy
  only:
    - main
  tags:
    - macos

deploy_android_testflight:
  stage: testflight
  dependencies:
    - package_android
  script:
    - cd android/
    - bundle install
    - bundle exec fastlane deploy_testflight
  only:
    - testflight
  tags:
    - macos

# iOS Packaging
package_ios:
  stage: package
  dependencies:
    - build_sync
  script:
    - cd ios/App/
    - bundle install
    - bundle exec fastlane package
  artifacts:
    paths:
      - App.ipa
  only:
    - main
    - testflight
  tags:
    - macos

# iOS Deployment
deploy_ios_release:
  stage: release
  dependencies:
    - package_ios
    - screenshots_ios
  script:
    - cd ios/App/
    - bundle install
    - bundle exec fastlane deploy
  only:
    - main
  tags:
    - macos

deploy_ios_testflight:
  stage: release
  dependencies:
    - package_ios
  script:
    - cd ios/App/
    - bundle install
    - bundle exec fastlane deploy_testflight
  only:
    - testflight
  tags:
    - macos

# Gitlab Release
deploy_gitlab_release:
  stage: release
  script:
    - git tag -a $SELENE_VERSION -m "Version $SELENE_VERSION"
    - git push origin $SELENE_VERSION
  only:
    - main
