const ACTION_TYPES = {
  UDPATE_WALLET: "UDPATE_WALLET",
  UPDATE_BALANCE: "UPDATE_BALANCE",
  UPDATE_TEMP_TXID: "UPDATE_TEMP_TXID",
  UPDATE_TRANSACTION_PAD_BALANCE: "UPDATE_TRANSACTION_PAD_BALANCE",
  UPDATE_TRANSACTION_PAD_STATE: "UPDATE_TRANSACTION_PAD_STATE",
  UPDATE_TRANSACTION_PAD_ERROR: "UPDATE_TRANSACTION_PAD_ERROR",
  TOGGLE_IS_CRYPTO_DENOMINATED: "TOGGLE_IS_CRYPTO_DENOMINATED",
};

export default ACTION_TYPES;
