import COLOURS from "./colours";
import SPACING from "./spacing";

const TYPOGRAPHY = {
  title: {
    fontFamily: "Montserrat_700Bold",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 50,
    marginBottom: SPACING.ten,
  },
  subtitle: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 25,
    marginBottom: SPACING.twentyFive,
  },
  header: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 18,
  },
  whiteLink: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 18,
    textDecorationLine: "underline",
    marginTop: SPACING.ten,
    marginBottom: SPACING.ten,
  },
  h1: {
    fontFamily: "Montserrat_600SemiBold",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 28,
    marginBottom: SPACING.ten,
  },
  h1black: {
    fontFamily: "Montserrat_600SemiBold",
    textAlign: "center" as const,
    color: COLOURS.black,
    fontSize: 28,
    marginBottom: SPACING.ten,
  },
  h1red: {
    fontFamily: "Montserrat_600SemiBold",
    textAlign: "center" as const,
    color: COLOURS.errorRed,
    fontSize: 28,
    marginBottom: SPACING.ten,
  },
  h2: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 22,
    marginBottom: SPACING.ten,
  },
  h2Left: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "left" as const,
    color: COLOURS.white,
    fontSize: 22,
    marginBottom: SPACING.ten,
  },
  h2black: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.black,
    fontSize: 22,
    marginBottom: SPACING.ten,
  },
  h2Green: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.bchGreen,
    fontSize: 22,
    marginBottom: SPACING.ten,
  },
  menuHeaderGreen: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.bchGreen,
    fontSize: 22,
  },
  subMenuHeaderWhite: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 16,
  },
  subMenuHeaderWhite14: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 14,
  },
  subMenuHeaderWhite12: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 12,
  },
  p: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.black,
    fontSize: 16,
    marginBottom: SPACING.ten,
  },
  pLeft: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "left" as const,
    color: COLOURS.black,
    fontSize: 16,
    marginBottom: SPACING.ten,
  },
  pWhite: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 16,
    marginBottom: SPACING.ten,
  },
  pUnderlined: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.black,
    fontSize: 16,
    marginBottom: SPACING.ten,
    textDecorationLine: "underline",
  },
  pWhiteUnderlined: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.white,
    fontSize: 16,
    marginBottom: SPACING.ten,
    textDecorationLine: "underline",
  },
  pGreenUnderlined: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.bchGreen,
    fontSize: 16,
    marginBottom: SPACING.ten,
    textDecorationLine: "underline",
  },
  pWhiteLeft: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "left" as const,
    color: COLOURS.white,
    fontSize: 16,
    marginBottom: SPACING.ten,
  },
  pRed: {
    fontFamily: "Montserrat_500Medium",
    textAlign: "center" as const,
    color: COLOURS.errorRed,
    fontSize: 16,
    marginBottom: SPACING.ten,
  },
  spacer: {
    height: SPACING.fifteen,
  },
};

export default TYPOGRAPHY;
