# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a build to TestFlight"
  lane :beta do
    ensure_git_status_clean

    increment_build_number(xcodeproj: "App.xcodeproj", build_number: ENV['CI_JOB_ID'])
    commit_version_bump(xcodeproj: "App.xcodeproj")
    
    sync_code_signing(type: "appstore")
    build_app(scheme: "App")

    add_git_tag
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    ensure_git_status_clean

    increment_build_number(xcodeproj: "App.xcodeproj", build_number: ENV['CI_JOB_ID'])
    commit_version_bump(xcodeproj: "App.xcodeproj")
    
    sync_code_signing(type: "appstore")
    build_app(scheme: "App")

    add_git_tag
    upload_to_app_store
  end
end
