# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build .ipa package for iOS"
  lane :package do
    sh "../../../scripts/ios-archive-fix.sh"
    sync_code_signing(type: "appstore")
    build_app(scheme: "App")
  end

  desc "Push a build to TestFlight"
  lane :deploy_testflight do
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :deploy do
    upload_to_app_store
  end
end
