# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:android)

platform :android do
  desc "Build .aab and .apk packages for current version"
  lane :package do
    gradle(task: "clean")

    gradle(
        task: "bundle",
        build_type: "Release",
        print_command: false,
        properties: {
            "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE"],
            "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
            "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
            "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"]
        }
    )

    gradle(
        task: "assemble",
        build_type: "Release",
        print_command: false,
        properties: {
            "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE"],
            "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
            "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
            "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"]
        }
    )
  end

  desc "Generates screenshots"
  lane :screenshots do
    gradle(task: "test")
  end

  desc "Submit a new Release Candidate to Google Play Beta Track"
  lane :deploy_testflight do
    changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
    upload_to_play_store(track: "beta",
        aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(track: "production",
        aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
