# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal build"
  lane :internal do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: "internal")
  end

  desc "Submit a new Release Candidate to Google Play Beta Track"
  lane :beta do
    changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: "beta")
  end

  desc "Deploy a new version to the Google Play"
  lane :release do
    upload_to_play_store(track: "beta", track_promote_to: "production")
  end
end
