# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build .aab and .apk packages for current version"
  lane :package do
    gradle(task: "clean")

    gradle(
        task: "bundle",
        build_type: "Release"
    )

    gradle(
        task: "package",
        build_type: "Release"
    )


  desc "Generates screenshots"
  lane :screenshots do
    gradle(task: "test")
  end

  desc "Submit a new Release Candidate to Google Play Beta Track"
  lane :deploy_beta do
    changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: "beta")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(track: "production")
  end
end
